=== junglesta/junglestar/.astro/collections/offers.schema.json
{
  "$ref": "#/definitions/offers",
  "definitions": {
    "offers": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "permalink": {
          "type": "string"
        },
        "question": {
          "type": "string"
        },
        "publish": {
          "type": "boolean"
        },
        "bestseller": {
          "type": "boolean"
        },
        "bestvalue": {
          "type": "boolean"
        },
        "product": {
          "type": "object",
          "properties": {
            "group": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "subname": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            },
            "starting_at": {
              "type": "string"
            },
            "starting_at_rp": {
              "type": "string"
            },
            "starting_at_agent": {
              "type": "string"
            },
            "agent_gets": {
              "type": "string"
            },
            "demo_url": {
              "type": "string",
              "format": "uri"
            }
          },
          "required": [
            "group",
            "name",
            "type",
            "subname",
            "desc",
            "starting_at",
            "starting_at_rp",
            "starting_at_agent",
            "agent_gets",
            "demo_url"
          ],
          "additionalProperties": false
        },
        "selling_points": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "slug",
        "title",
        "description",
        "permalink",
        "question",
        "publish",
        "bestseller",
        "bestvalue",
        "product",
        "selling_points"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== junglesta/junglestar/src/data/pricing/pricing_landing.json
{
	"name": "landing page",
	"slug": "landing-page",
	"title": "amazing landing page",
	"type": "",
	"description": "Junglestar is a small, flexible, web agency. We deal with information architecture, screen design, code and deploy. We offer landing page websites at a competitive prices.",
	"permalink": "/offer/landing-page",
	"question": "&quot;Need website.<br>How much?&quot;",
	"publish": true,
	"bestseller": false,
	"bestvalue": true,
	"product": {
		"group": "design",
		"name": "Compact Website",
		"type": "All-included package",
		"subname": "Quality website template. Name, Hosting and SSL included.",
		"desc": "We load your data, process everything and produce a spicy landing page ready to hit. The perfect digital brochure with zero maintenance cost!",
		"starting_at": "590",
		"starting_at_rp": "4.900.000",
		"starting_at_agent": "3.900.000",
		"agent_gets": "1.000.000",
		"demo_url": "https://amazing-single.junglestar.org/"
	},
	"selling_points": {
		"sp01": "Full landing page.",
		"sp02": "Designed for phones... and desktops.",
		"sp03": "Social media friendly.",
		"sp04": "SEO optimised.",
		"sp05": "Domain name.",
		"sp06": "Hosting on global CDN.",
		"sp07": "Secure SLL/https.",
		"sp08": "Sustainable Web Design."
	}
}

=== junglesta/junglestar/src/data/pricing/pricing_fullsite.json
{
	"name": "full site",
	"slug": "full-site",
	"title": "amazing full site",
	"type": "",
	"description": "We are a small, flexible, web agency. We craft information architecture, screen design, write code and deploy it. We offer full website solutions all-included.",
	"permalink": "/offer/full-site",
	"question": "&quot;I need a website and<br>I have questions...&quot;",
	"publish": true,
	"bestseller": true,
	"bestvalue": false,
	"product": {
		"group": "design",
		"name": "Amazing Website",
		"type": "All-included package",
		"subname": "Quality website template. Name, Hosting and SSL included.",
		"desc": "We load your look and products data, process everything and produce a clean performant website ready to compete.",
		"starting_at": "990",
		"starting_at_rp": "9.900.000",
		"starting_at_agent": "7.900.000",
		"agent_gets": "2.000.000",
		"demo_url": "https://amazing-days.junglestar.org/"
	},
	"selling_points": {
		"sp01": "Full website.",
		"sp02": "Social media friendly.",
		"sp03": "SEO optimised.",
		"sp04": "Domain name.",
		"sp05": "Hosting on global CDN.",
		"sp06": "Secure SLL/https.",
		"sp07": "Data entry.",
		"sp08": "Editing system for collaborators.",
		"sp09": "Sustainable Web Design."
	}
}

=== junglesta/junglestar/src/data/pricing/pricing_custom.json
{
  "name": "custom",
  "slug": "custom",
  "title": "amazing custom design",
  "type": "",
  "description": "We are a small, flexible, web agency. We offer top quality custom designed websites at reasonable prices. We grow relationships with clients.",
  "permalink": "/offer/custom",
  "question": "&quot;Yes I want this,<br>that and also...&quot;",
  "publish": true,
  "bestseller": false,
  "bestvalue": false,
  "product": {
    "group": "design",
    "name": "Awesome Design",
    "type": "All-included package",
    "subname": "Customised design for your needs. Name, Hosting and SSL included.",
    "desc": "We craft a special design for your brand, produce & develop a well thought user experiences by embracing your existing look and brand identity.",
    "starting_at": "3.990",
    "starting_at_rp": "14.900.000",
    "starting_at_agent": "11.900.000",
    "agent_gets": "3.000.000",
    "demo_url": "https://binocle.it/?ref=junglestar"
  },
  "selling_points": {
    "sp01": "Responsive full website.",
    "sp02": "Social media friendly.",
    "sp03": "SEO optimised.",
    "sp04": "Domain name.",
    "sp05": "Hosting on global CDN.",
    "sp06": "Secure SLL/https.",
    "sp07": "Data entry.",
    "sp08": "Editing system for collaborators.",
    "sp09": "Customised architecture & functionalities.",
    "sp10": "Your Company look & feel!",
    "sp11": "Sustainable Web Design."
  }
}
